//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galeri_Otomasyon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GaleriEntities1 : DbContext
    {
        public GaleriEntities1()
            : base("name=GaleriEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Araçlar> Araçlar { get; set; }
        public DbSet<Kullanicilar> Kullanicilars { get; set; }
        public DbSet<Müşteriler> Müşteriler { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Şubeler> Şubeler { get; set; }
    }
}
