//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galeri_Otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Şubeler
    {
        public Şubeler()
        {
            this.Araçlar = new HashSet<Araçlar>();
        }
    
        public int SubeNo { get; set; }
        public string SubeAdi { get; set; }
        public Nullable<int> CalisanSayisi { get; set; }
        public Nullable<decimal> SubeCiro { get; set; }
        public Nullable<int> MusteriNo { get; set; }
    
        public virtual ICollection<Araçlar> Araçlar { get; set; }
        public virtual Müşteriler Müşteriler { get; set; }
    }
}
